//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avvir.DataLayer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentBody
    {
        public System.Guid GUID { get; set; }
        public System.Guid HeaderGUID { get; set; }
        public System.Guid RowGUIDCol { get; set; }
        public byte[] Body { get; set; }
    
        public virtual AttachmentHeader AttachmentHeader { get; set; }
    }
}
