//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avvir.DataLayer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid GUID { get; set; }
        public System.Guid MessageGUID { get; set; }
        public System.Guid AuthorGUID { get; set; }
        public string Body { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Message Message { get; set; }
    }
}
