CREATE TABLE [dbo].[AttachmentBody] (
    [GUID] UNIQUEIDENTIFIER           CONSTRAINT [DF_AttachmentBody_GUID] DEFAULT (newsequentialid()) ROWGUIDCOL NOT NULL,
    [Body] VARBINARY (MAX) FILESTREAM NOT NULL,
    CONSTRAINT [PK_AttachmentBody] PRIMARY KEY CLUSTERED ([GUID] ASC),
    UNIQUE NONCLUSTERED ([GUID] ASC)
) FILESTREAM_ON [UserAttachments];

