CREATE TABLE [dbo].[GroupType] (
    [GUID] UNIQUEIDENTIFIER CONSTRAINT [DF_GroupType_GUID] DEFAULT (newsequentialid()) NOT NULL,
    [Name] NVARCHAR (50)    NOT NULL,
    CONSTRAINT [PK_GroupType] PRIMARY KEY CLUSTERED ([GUID] ASC)
);

