CREATE TABLE [dbo].[GroupRole] (
    [GUID] UNIQUEIDENTIFIER CONSTRAINT [DF_GroupRole_GUID] DEFAULT (newsequentialid()) NOT NULL,
    [Name] NVARCHAR (50)    NOT NULL,
    [Code] NVARCHAR (10)    NOT NULL,
    CONSTRAINT [PK_GroupRole] PRIMARY KEY CLUSTERED ([GUID] ASC)
);

