//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avvir.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvvirModel : DbContext
    {
        public AvvirModel()
            : base("name=AvvirModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<ContactList> ContactList { get; set; }
        public virtual DbSet<GroupDict> GroupDict { get; set; }
        public virtual DbSet<GroupType> GroupType { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<UserGroupRole> UserGroupRole { get; set; }
        public virtual DbSet<Token> Token { get; set; }
    }
}
