//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avvir.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroupRole
    {
        public System.Guid GUID { get; set; }
        public System.Guid AccountGUID { get; set; }
        public System.Guid GroupGUID { get; set; }
        public System.Guid GroupRoleGUID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual GroupDict GroupDict { get; set; }
    }
}
